-- Populate Loops with Nigerian Universities (Top 50+)
-- Includes Domains and Standardized Terminology (Plug/Buyer)

INSERT INTO campuses (name, slug, domain, type, location, terms) VALUES
('Veritas University', 'veritas', 'veritas.edu.ng', 'private', 'Abuja', '{"sellerName": "Plug", "buyerName": "Buyer", "listingName": "Drop", "communityName": "Campus Loop"}'::jsonb),
('University of Lagos', 'unilag', 'unilag.edu.ng', 'public', 'Lagos', '{"sellerName": "Plug", "buyerName": "Buyer", "listingName": "Drop", "communityName": "The Hub"}'::jsonb),
('University of Ibadan', 'ui', 'ui.edu.ng', 'public', 'Ibadan', '{"sellerName": "Plug", "buyerName": "Buyer", "listingName": "Drop", "communityName": "The Hub"}'::jsonb),
('Covenant University', 'covenant', 'covenantuniversity.edu.ng', 'private', 'Ota', '{"sellerName": "Plug", "buyerName": "Buyer", "listingName": "Listing", "communityName": "Campus Loop"}'::jsonb),
('Babcock University', 'babcock', 'babcock.edu.ng', 'private', 'Ilishan-Remo', '{"sellerName": "Plug", "buyerName": "Buyer", "listingName": "Listing"}'::jsonb),
('Ahmadu Bello University', 'abu', 'abu.edu.ng', 'public', 'Zaria', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('University of Nigeria, Nsukka', 'unn', 'unn.edu.ng', 'public', 'Nsukka', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Obafemi Awolowo University', 'oau', 'oauife.edu.ng', 'public', 'Ife', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('University of Benin', 'uniben', 'uniben.edu.ng', 'public', 'Benin City', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('University of Ilorin', 'unilorin', 'unilorin.edu.ng', 'public', 'Ilorin', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Federal University of Technology, Akure', 'futa', 'futa.edu.ng', 'public', 'Akure', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Federal University of Technology, Minna', 'futminna', 'futminna.edu.ng', 'public', 'Minna', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Federal University of Technology, Owerri', 'futo', 'futo.edu.ng', 'public', 'Owerri', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Lagos State University', 'lasu', 'lasu.edu.ng', 'public', 'Ojo', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Bayero University Kano', 'buk', 'buk.edu.ng', 'public', 'Kano', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('University of Port Harcourt', 'uniport', 'uniport.edu.ng', 'public', 'Port Harcourt', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('University of Jos', 'unijos', 'unijos.edu.ng', 'public', 'Jos', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Nnamdi Azikiwe University', 'unizik', 'unizik.edu.ng', 'public', 'Awka', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('University of Calabar', 'unical', 'unical.edu.ng', 'public', 'Calabar', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('University of Abuja', 'uniabuja', 'uniabuja.edu.ng', 'public', 'Abuja', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Landmark University', 'landmark', 'lmu.edu.ng', 'private', 'Omu-Aran', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Pan-Atlantic University', 'pau', 'pau.edu.ng', 'private', 'Lagos', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('American University of Nigeria', 'aun', 'aun.edu.ng', 'private', 'Yola', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Bowen University', 'bowen', 'bowen.edu.ng', 'private', 'Iwo', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Redeemer''s University', 'run', 'run.edu.ng', 'private', 'Ede', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Afe Babalola University', 'abuad', 'abuad.edu.ng', 'private', 'Ado-Ekiti', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Nile University of Nigeria', 'nile', 'nileuniversity.edu.ng', 'private', 'Abuja', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Baze University', 'baze', 'bazeuniversity.edu.ng', 'private', 'Abuja', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Kwara State University', 'kwasu', 'kwasu.edu.ng', 'public', 'Malete', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Ladoke Akintola University of Technology', 'lautech', 'lautech.edu.ng', 'public', 'Ogbomoso', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Rivers State University', 'rsu', 'rsu.edu.ng', 'public', 'Port Harcourt', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Enugu State University of Science and Technology', 'esut', 'esut.edu.ng', 'public', 'Enugu', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Ambrose Alli University', 'aau', 'aauekpoma.edu.ng', 'public', 'Ekpoma', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Delta State University', 'delsu', 'delsu.edu.ng', 'public', 'Abraka', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Abia State University', 'absu', 'abiastateuniversity.edu.ng', 'public', 'Uturu', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Ekiti State University', 'eksu', 'eksu.edu.ng', 'public', 'Ado-Ekiti', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Olabisi Onabanjo University', 'oou', 'oouagoiwoye.edu.ng', 'public', 'Ago-Iwoye', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Adekunle Ajasin University', 'aaua', 'aaua.edu.ng', 'public', 'Akungba-Akoko', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Benue State University', 'bsum', 'bsum.edu.ng', 'public', 'Makurdi', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Kaduna State University', 'kasu', 'kasu.edu.ng', 'public', 'Kaduna', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Imo State University', 'imsu', 'imsu.edu.ng', 'public', 'Owerri', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Ebonyi State University', 'ebsu', 'ebsu.edu.ng', 'public', 'Abakaliki', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Niger Delta University', 'ndu', 'ndu.edu.ng', 'public', 'Wilberforce Island', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Tai Solarin University of Education', 'tasued', 'tasued.edu.ng', 'public', 'Ijebu-Ode', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Osuns State University', 'uniosun', 'uniosun.edu.ng', 'public', 'Osogbo', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Kogi State University', 'ksu', 'ksu.edu.ng', 'public', 'Anyigba', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Benson Idahosa University', 'biu', 'biu.edu.ng', 'private', 'Benin City', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Igbinedion University', 'iuokada', 'iuokada.edu.ng', 'private', 'Okada', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Madonna University', 'madonna', 'madonnauniversity.edu.ng', 'private', 'Elele', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Ajayi Crowther University', 'acu', 'acu.edu.ng', 'private', 'Oyo', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Al-Hikmah University', 'alhikmah', 'alhikmah.edu.ng', 'private', 'Ilorin', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb),
('Lead City University', 'lcu', 'lcu.edu.ng', 'private', 'Ibadan', '{"sellerName": "Plug", "buyerName": "Buyer"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET 
    domain = EXCLUDED.domain,
    type = EXCLUDED.type,
    location = EXCLUDED.location,
    terms = EXCLUDED.terms;
